name: build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with maven
        run: >
          ./mvnw clean install
      - name: Upload the artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: query-executor

  sonar:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run sonarcloud analysis
        run: >
          ./mvnw verify sonar:sonar
          -Dsonar.sources=src/main/scala
          -Dsonar.tests=src/test/scala
          -Dsonar.scala.coverage.reportPaths=target/scoverage.xml
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=aphp
          -Dsonar.projectKey=aphp_Cohort360-QueryExecutor
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
